version: '2.1'
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  configserver:
    image: prlwk/serverconfig:0.0.1-SNAPSHOT
    ports:
      - "8088:8080"
    environment:
      SPRING_CLOUD_CONFIG_URL: http://configserver:8088
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: prlwk/eurekaserver:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
    ports:
      - "8085:8080"
    networks:
       backend:
         aliases:
          - "eurekaserver"
  bookservice:
    image: prlwk/book-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8081"
    networks:
      - backend
  authorservice:
    image: prlwk/author-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8081:8080"
    networks:
      - backend
  reviewservice:
    image: prlwk/review-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8082:8080"
    networks:
      - backend
  userservice:
    image: prlwk/user-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8083:8080"
    networks:
      - backend
networks:
  backend:
    driver: bridge
