spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/user
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 28012003Nastia
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8085/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: user-instance
server:
  port: 8070